// ─── Ripple Wellness — Default UI Strings ────────────────────────────────────
// All user-facing text in the app, organized by feature area.
// Keys use snake_case. Dynamic placeholders use {name} syntax.
// Import via: import { DEFAULT_STRINGS, StringKey, StringMap } from "./defaults";

export const DEFAULT_STRINGS = {

  // ── APP ──────────────────────────────────────────────────────────────────
  app_name: "Ripple Wellness",

  // ── AUTH ─────────────────────────────────────────────────────────────────
  auth_login_title: "Welcome back",
  auth_login_subtitle: "Sign in to your account",
  auth_email_placeholder: "Email",
  auth_password_placeholder: "Password",
  auth_login_button: "Sign in",
  auth_no_account: "Don't have an account?",
  auth_sign_up_link: "Sign up",
  auth_signup_title: "Create account",
  auth_signup_subtitle: "Start tracking your wellness",
  auth_name_placeholder: "Your name",
  auth_confirm_password_placeholder: "Confirm password",
  auth_signup_button: "Create account",
  auth_already_have_account: "Already have an account?",
  auth_sign_in_link: "Sign in",
  auth_error_invalid_credentials: "Invalid email or password.",
  auth_error_passwords_dont_match: "Passwords don't match.",
  auth_error_email_required: "Email is required.",
  auth_error_password_required: "Password is required.",
  auth_error_name_required: "Name is required.",

  // ── ONBOARDING ────────────────────────────────────────────────────────────
  onboarding_welcome_title: "Welcome to Ripple",
  onboarding_welcome_desc: "Your private wellness hub — track glucose, mood, meals, sleep, habits, and more.",
  onboarding_privacy_note: "Everything you log stays on your personal server. Nothing is sold or shared.",
  onboarding_get_started: "Get Started",
  onboarding_skip: "Skip",
  onboarding_next: "Next",
  onboarding_done: "Done",

  // ── NAVIGATION / TABS ─────────────────────────────────────────────────────
  nav_overview: "Overview",
  nav_health: "Health",
  nav_meals: "Meals",
  nav_life: "Life",
  nav_finance: "Finance",
  nav_mindfulness: "Mindfulness",
  nav_friends: "Friends",
  nav_settings: "Settings",
  nav_challenges: "Challenges",
  nav_leaderboard: "Leaderboard",
  nav_insights: "Insights",
  nav_trends: "Trends",
  nav_history: "History",
  nav_exercise: "Exercise",
  nav_completed: "Completed",

  // ── OVERVIEW / DASHBOARD ──────────────────────────────────────────────────
  overview_customize_button: "Customize",
  overview_good_morning: "Good morning",
  overview_good_afternoon: "Good afternoon",
  overview_good_evening: "Good evening",
  overview_daily_summary: "Daily Summary",
  overview_no_data_yet: "No data yet — start logging to see your summary here.",
  overview_streak_label: "Day streak",
  overview_today: "Today",

  // ── HEALTH SCREEN ─────────────────────────────────────────────────────────
  health_glucose_title: "Glucose",
  health_time_in_range: "Time in Range",
  health_avg_glucose: "Avg Glucose",
  health_readings_label: "Readings",
  health_low_label: "Low",
  health_high_label: "High",
  health_steps_title: "Steps",
  health_steps_today: "Steps today",
  health_steps_goal: "Daily goal",
  health_sleep_title: "Sleep",
  health_sleep_hours: "Hours slept",
  health_heart_rate_title: "Heart Rate",
  health_heart_rate_avg: "Avg BPM",
  health_heart_rate_peak: "Peak BPM",
  health_heart_rate_resting: "Resting BPM",
  health_no_readings: "No readings yet today.",
  health_add_reading: "Add reading",
  health_manual_entry: "Manual entry",
  health_glucose_in_range: "In range",
  health_glucose_above_range: "Above range",
  health_glucose_below_range: "Below range",

  // ── HEALTH TAB (MEDICATION) ──────────────────────────────────────────────
  med_todays_schedule: "Today's Schedule",
  med_my_medications: "My Medications",
  med_add_medication: "+ Add medication",
  med_import_csv: "Import from CSV / Excel",
  med_select_mode_label: "Select",
  med_done_select_label: "Done",
  med_mark_all: "Mark all",
  med_mark_selected_taken: "Mark {count} selected as taken",
  med_next_dose_prefix: "Next: {time}",
  med_bucket_morning: "Morning",
  med_bucket_midday: "Midday",
  med_bucket_evening: "Evening",
  med_bucket_custom: "Custom",
  med_frequency_daily: "Daily",
  med_frequency_weekly: "Weekly",
  med_schedule_label: "Schedule",
  med_prn_label: "PRN / As Needed",
  med_prn_on: "PRN ON",
  med_prn_off: "Off",
  med_prn_note: "This med won't affect your adherence score.",
  med_pick_day_of_week: "Pick a day of week:",
  med_day_sun: "Sun",
  med_day_mon: "Mon",
  med_day_tue: "Tue",
  med_day_wed: "Wed",
  med_day_thu: "Thu",
  med_day_fri: "Fri",
  med_day_sat: "Sat",
  med_time_morning: "Morning",
  med_time_midday: "Midday",
  med_time_evening: "Evening",
  med_time_custom: "Custom",
  med_custom_time_placeholder: "Custom time (HH:MM)",
  med_modal_add_title: "Add Medication",
  med_modal_edit_title: "Edit Medication",
  med_name_placeholder: "Medication name",
  med_brand_name_placeholder: "Brand name (optional)",
  med_generic_name_placeholder: "Generic name (optional)",
  med_dosage_placeholder: "Dosage (e.g. 10mg)",
  med_purpose_placeholder: "Purpose (optional)",
  med_prescriber_placeholder: "Prescriber (optional)",
  med_refill_date_placeholder: "Refill date (YYYY-MM-DD)",
  med_notes_placeholder: "Notes (optional)",
  med_category_label: "Category",
  med_saving: "Saving…",
  med_save_button: "Save Medication",
  med_save_changes_button: "Save Changes",
  med_remove_alert_title: "Remove medication?",
  med_remove_alert_message: "This will hide the medication from your schedule.",
  med_remove_alert_confirm: "Remove",
  med_remove_alert_cancel: "Cancel",
  med_error_name_required: "Name required",
  med_error_save_failed: "Failed to save",
  med_purpose_prefix: "Purpose: {purpose}",
  med_prescriber_prefix: "Dr. {name}",
  med_brand_prefix: "Brand: {name}",
  med_generic_prefix: "Generic: {name}",
  med_prn_subtitle: "As needed (PRN)",
  med_no_schedule: "No schedule",
  med_weekly_prefix: "Weekly — {day}",
  med_refill_overdue: "Refill overdue",
  med_refill_in_days: "Refill in {count} day",
  med_refill_in_days_plural: "Refill in {count} days",
  med_status_active: "Active",
  med_status_stopped: "Stopped",
  med_status_paused: "Paused",
  med_no_fda_label: "No FDA label information available for this medication.",
  med_fda_disclaimer: "Per the FDA-approved drug label. Talk to your prescriber about any questions.",
  med_fda_section_indications: "Indications",
  med_fda_section_dosage: "Dosage",
  med_fda_section_warnings: "Warnings",
  med_fda_section_adverse: "Adverse Reactions",

  // ── HEALTH TAB (CYCLE) ────────────────────────────────────────────────────
  cycle_getting_started_title: "Getting started with Cycle Tracking",
  cycle_getting_started_body: "Log your flow, symptoms, and mood each day to see predictions and patterns.",
  cycle_learn_more: "Learn more",
  cycle_dismiss: "Dismiss",
  cycle_learn_more_alert_title: "Cycle Tracking",
  cycle_learn_more_alert_body: "Tap any day on the calendar to log flow, symptoms, mood, and energy. After 3+ cycles, you will see period predictions.",
  cycle_no_log_for_day: "No log for this day.",
  cycle_log_this_day: "Log this day",
  cycle_edit_entry: "Edit Entry",
  cycle_insights_title: "Cycle Insights",
  cycle_average_cycle: "Average cycle: {n} days",
  cycle_average_period: "Average period: {n} days",
  cycle_regularity_label: "Regularity:",
  cycle_regularity_consistent: "Consistent",
  cycle_regularity_irregular: "Irregular",
  cycle_top_symptoms_label: "Top symptoms:",
  cycle_based_on_cycles: "Based on {n} cycles",
  cycle_history_title: "Cycle History",
  cycle_insight_tentative: "Based on limited data — may change as more cycles are logged.",
  cycle_phase_suffix: "{date} · {phase} phase",
  cycle_flow_intensity_label: "Flow intensity",
  cycle_symptoms_label: "Symptoms",
  cycle_add_custom_symptom_placeholder: "Add custom symptom",
  cycle_add_button: "Add",
  cycle_energy_label: "Energy level",
  cycle_mood_label: "Mood",
  cycle_mood_search_placeholder: "Search moods…",
  cycle_notes_label: "Notes",
  cycle_notes_placeholder: "How are you feeling today?",
  cycle_save_button: "Save",
  cycle_delete_log: "Delete this log",
  cycle_delete_alert_title: "Delete log?",
  cycle_delete_alert_message: "Remove this day's log?",
  cycle_delete_alert_confirm: "Delete",
  cycle_delete_alert_cancel: "Cancel",
  cycle_show_more: "View {n} more",
  cycle_show_less: "Show less",
  cycle_legend_period: "Period",
  cycle_legend_next_period: "Next period",
  cycle_legend_predicted_days: "Predicted days",
  cycle_legend_symptoms: "Symptoms",
  cycle_legend_mood: "Mood",
  cycle_flow_tag: "Flow: {value}",
  cycle_mood_tag: "Mood: {value}",
  cycle_energy_tag: "Energy: {value}/10",
  cycle_symptoms_summary: "Symptoms: {list}",

  // ── MEALS SCREEN ──────────────────────────────────────────────────────────
  meals_search_placeholder: "search food...",
  meals_search_button: "SEARCH",
  meals_scan_barcode: "SCAN BARCODE",
  meals_add_manually: "+ ADD MANUALLY",
  meals_food_name_label: "Food name",
  meals_calories_label: "CALORIES",
  meals_carbs_label: "CARBS",
  meals_sugar_label: "SUGAR",
  meals_caffeine_label: "CAFFEINE",
  meals_sodium_label: "SODIUM",
  meals_drinks_section: "DRINKS",
  meals_your_usual_section: "YOUR USUAL",
  meals_log_a_meal_title: "Log a meal",
  meals_alcohol_label: "Alcohol",
  meals_todays_meals_title: "Today's meals",
  meals_no_meals_yet: "No meals logged yet today.",
  meals_food_report_title: "Food Report",
  meals_spikes_glucose_most: "SPIKES GLUCOSE MOST",
  meals_stays_stable: "STAYS STABLE",
  meals_already_logged_today: "Already logged today",
  meals_save_failed: "Your meal wasn't saved. Please try again.",
  meals_drink_save_failed: "Couldn't log that drink. Please try again.",
  meals_recipe_save_failed: "Couldn't log that recipe. Please try again.",
  meals_high_response_badge: "HIGH RESPONSE",
  meals_no_glucose_readings: "No glucose readings found for this meal window.",

  // ── FINANCE SCREEN ────────────────────────────────────────────────────────
  finance_spent_today: "SPENT TODAY",
  finance_spent_this_week: "SPENT THIS WEEK",
  finance_period_today: "Today",
  finance_period_week: "This Week",
  finance_where_it_went: "Where it went",
  finance_month_forecast: "Month forecast",
  finance_projected_label: "PROJECTED",
  finance_budget_label: "BUDGET",
  finance_over_budget: "over budget at this pace",
  finance_under_budget: "under budget at this pace",
  finance_heads_up: "Heads up",
  finance_mood_suggestion_yes: "Yes, tag it",
  finance_mood_suggestion_no: "No thanks",
  finance_nothing_logged_today: "Nothing logged today",
  finance_nothing_logged_week: "Nothing this week",
  finance_log_expense_title: "Log expense",
  finance_save_expense: "Save expense",
  finance_save_changes: "Save changes",
  finance_delete_entry: "Delete entry",
  finance_customize_title: "Customize Finance",
  finance_amount_placeholder: "Amount ($)",
  finance_category_placeholder: "Category",
  finance_note_placeholder: "Note (optional)",
  finance_date_label: "Date",

  // ── FRIENDS SCREEN ────────────────────────────────────────────────────────
  friends_my_username_label: "MY USERNAME",
  friends_your_username_label: "YOUR USERNAME",
  friends_username_hint: "Friends can find you using this name.",
  friends_username_empty_hint: "Set a username so friends can find you.",
  friends_choose_username_placeholder: "Choose a username",
  friends_add_friend_title: "ADD A FRIEND",
  friends_search_placeholder: "Email or username",
  friends_requests_title: "FRIEND REQUESTS ({count})",
  friends_accept: "Accept",
  friends_decline: "Decline",
  friends_my_friends_title: "MY FRIENDS",
  friends_no_friends_yet: "No friends yet. Send a request above to get started!",
  friends_sharing_label: "Sharing:",
  friends_nothing_yet: "nothing yet",
  friends_activity_title: "FRIEND ACTIVITY",
  friends_quiet_week: "Quiet week so far — no streaks to celebrate yet.",
  friends_leaderboards_title: "LEADERBOARDS",
  friends_leaderboard_note: "Only steps, exercise, hobbies, and books are compared with your friends.",
  friends_challenges_title: "CHALLENGES",
  friends_see_challenges: "See Challenges",
  friends_nudge_message: "{name} nudged you!",

  // ── FRIENDS ONBOARDING ────────────────────────────────────────────────────
  friends_onboarding_welcome_title: "Connect with Friends",
  friends_onboarding_welcome_desc: "Compare progress, cheer each other on, and stay accountable — all while keeping your health data completely private.",
  friends_onboarding_privacy_note: "Only data you explicitly choose to share is ever visible to friends.",
  friends_onboarding_get_started: "Get Started",
  friends_onboarding_choose_username_title: "Choose a Username",
  friends_onboarding_username_rules: "Pick a unique name your friends will recognize. 3–20 characters, letters and numbers only.",
  friends_onboarding_save_continue: "Save & Continue",
  friends_onboarding_skip: "Skip for Now",
  friends_onboarding_what_to_share_title: "What to Share",
  friends_onboarding_sharing_desc: "Choose which stats your friends can see on leaderboards. You can change this any time.",
  friends_onboarding_add_friend_title: "Add Your First Friend",
  friends_onboarding_continue_to_friends: "Continue to Friends",
  friends_onboarding_skip_for_now: "Skip for now",
  friends_onboarding_all_set_title: "You're all set!",
  friends_onboarding_open_friends: "Open Friends",

  // ── SOCIAL SETTINGS ───────────────────────────────────────────────────────
  social_privacy_banner: "Only data you choose to share is visible to friends. All other health data stays completely private.",
  social_share_with_friends_title: "SHARE WITH FRIENDS",
  social_share_steps_label: "Steps",
  social_share_steps_sub: "Weekly step totals on the leaderboard",
  social_share_exercise_label: "Exercise time",
  social_share_exercise_sub: "Weekly exercise minutes on the leaderboard",
  social_share_hobbies_label: "Hobbies",
  social_share_hobbies_sub: "Weekly hobby time on the leaderboard",
  social_share_books_label: "Books",
  social_share_books_sub: "Books finished this month on the leaderboard",
  social_leaderboard_note: "Turning off a category hides you from that leaderboard.",
  social_notifications_title: "SOCIAL NOTIFICATIONS",
  social_notify_reactions_label: "Reactions",
  social_notify_reactions_sub: "When a friend reacts to your leaderboard entry",
  social_notify_nudges_label: "Nudges",
  social_notify_nudges_sub: "When a friend sends you a nudge",
  social_notify_requests_label: "Friend requests",
  social_notify_requests_sub: "When someone sends you a friend request",
  social_notify_request_accepted_label: "Request accepted",
  social_notify_request_accepted_sub: "When someone accepts your friend request",
  social_notify_challenge_invites_label: "Challenge invites",
  social_notify_challenge_invites_sub: "When a friend invites you to a challenge",
  social_notify_challenge_updates_label: "Challenge updates",
  social_notify_challenge_updates_sub: "Progress updates from active challenges",
  social_notify_leaderboard_milestones_label: "Leaderboard milestones",
  social_notify_leaderboard_milestones_sub: "When you move up in rank",
  social_error_save: "Could not save social settings.",

  // ── LEADERBOARD SCREEN ────────────────────────────────────────────────────
  leaderboard_steps_label: "Steps This Week",
  leaderboard_exercise_label: "Exercise This Week",
  leaderboard_hobbies_label: "Hobbies This Week",
  leaderboard_books_label: "Books This Month",
  leaderboard_compared_with_friends: "Compared with your friends",
  leaderboard_your_position: "Your position: #{rank} — {value}",
  leaderboard_privacy_note: "Only data each person has chosen to share is visible here. All other health data stays completely private.",
  leaderboard_invite_friends_title: "Invite friends to compare!",
  leaderboard_invite_friends_body: "You need at least two people with shared data to see a leaderboard. Add friends from the Friends tab.",
  leaderboard_encouraging_note: "Keep it up — every bit of progress counts. The goal is to stay active together, not to race.",
  leaderboard_react_prompt: "REACT TO {name}",
  leaderboard_you_reacted: "you reacted",
  leaderboard_you_suffix: " (you)",

  // ── CHALLENGES SCREEN ─────────────────────────────────────────────────────
  challenges_new_challenge: "New Challenge",
  challenges_active_tab: "Active",
  challenges_past_tab: "Past",
  challenges_no_active: "No active challenges.",
  challenges_no_past: "No past challenges.",
  challenges_empty_title: "No challenges yet",
  challenges_empty_body: "Start a challenge with friends to stay motivated together.",
  challenges_create_first: "Create your first challenge",
  challenges_participants_label: "PARTICIPANTS",
  challenges_no_participants: "No participants yet.",
  challenges_your_progress: "Your progress: {value} — Rank #{rank}",
  challenges_keep_going: "Keep going — every bit of effort counts. The goal is to stay consistent, not to win.",
  challenges_leave_button: "Leave Challenge",
  challenges_leave_alert_title: "Leave challenge?",
  challenges_leave_alert_message: "You will be removed from this challenge.",
  challenges_leave_alert_confirm: "Leave",
  challenges_leave_alert_cancel: "Cancel",
  challenges_error_load: "Could not load challenge details.",

  // ── NEW CHALLENGE SCREEN ──────────────────────────────────────────────────
  new_challenge_title: "New Challenge",
  new_challenge_privacy_note: "Challenges are visible to all participants. Keep goal descriptions positive and encouraging.",
  new_challenge_title_label: "CHALLENGE TITLE",
  new_challenge_title_placeholder: "e.g. Step count showdown",
  new_challenge_category_label: "CATEGORY",
  new_challenge_goal_desc_label: "GOAL DESCRIPTION",
  new_challenge_goal_desc_placeholder: "Describe the challenge goal…",
  new_challenge_goal_value_label: "GOAL VALUE (OPTIONAL)",
  new_challenge_goal_value_hint: "Leave blank if the goal is qualitative or open-ended.",
  new_challenge_goal_value_placeholder: "e.g. 100000",
  new_challenge_date_range_label: "DATE RANGE",
  new_challenge_start_date_label: "START DATE",
  new_challenge_end_date_label: "END DATE",
  new_challenge_duration_1_week: "1 week",
  new_challenge_duration_2_weeks: "2 weeks",
  new_challenge_duration_1_month: "1 month",
  new_challenge_invite_label: "INVITE FRIENDS",
  new_challenge_invite_placeholder: "Select friends to invite...",
  new_challenge_create_button: "Create Challenge",
  new_challenge_error_title_required: "Challenge title is required.",
  new_challenge_error_category_required: "Please select a category.",
  new_challenge_error_goal_desc_required: "Goal description is required.",
  new_challenge_error_dates_required: "Please select start and end dates.",
  new_challenge_error_start_before_end: "Start date must be before end date.",
  new_challenge_success: "Challenge created!",
  new_challenge_error_create: "Could not create challenge.",

  // ── LIFE SCREEN ───────────────────────────────────────────────────────────
  life_books_title: "Books",
  life_hobbies_title: "Hobbies",
  life_add_book: "Add a book",
  life_add_hobby: "Add a hobby",
  life_search_books_placeholder: "Search books…",
  life_page_progress_label: "Page {current} of {total}",
  life_log_pages: "LOG",
  life_done_reading: "DONE ✓",
  life_book_completed: "Completed!",
  life_hobby_log_button: "LOG",
  life_this_week_label: "THIS WEEK",
  life_last_week_label: "LAST WEEK",
  life_minutes_short: "min",
  life_hours_short: "h",
  life_no_books: "No books in progress. Add one above!",
  life_no_hobbies: "No hobbies set up yet.",
  life_completed_archive: "Completed",

  // ── COMPLETED SCREEN ──────────────────────────────────────────────────────
  completed_empty: "Nothing completed yet — finish a book or mark a hobby complete to see it here.",
  completed_books_title: "BOOKS READ · {count}",
  completed_finished_date: "Finished {date}",
  completed_hobbies_title: "COMPLETED HOBBIES · {count}",
  completed_hobby_date: "Completed {date}",
  completed_remove_book_title: "Remove book?",
  completed_remove_book_message: "Remove this book from your completed list?",
  completed_remove_hobby_title: "Remove hobby?",
  completed_remove_hobby_message: "Remove this hobby from your completed list?",
  completed_remove_confirm: "Remove",
  completed_remove_cancel: "Cancel",

  // ── EXERCISE SCREEN ───────────────────────────────────────────────────────
  exercise_start_session: "Start Session",
  exercise_my_plan: "My Plan",
  exercise_this_week: "This Week",
  exercise_recent_sessions: "Recent Sessions",
  exercise_no_sessions: "No sessions yet — start one above!",
  exercise_session_duration_label: "Duration",
  exercise_session_exercises_label: "Exercises",
  exercise_session_sets_label: "Sets",
  exercise_plan_your_workout: "Plan your workout",
  exercise_no_plan_title: "No exercises planned",
  exercise_no_plan_body: "Add exercises below to build your workout, or begin now and log as you go.",
  exercise_add_exercise: "+ Add exercise",
  exercise_begin_workout: "Begin Workout",
  exercise_est_time_label: "EST. TIME",
  exercise_now_label: "NOW",
  exercise_exercises_label: "EXERCISES",
  exercise_cancel: "Cancel",
  exercise_search_placeholder: "Search exercises…",
  exercise_add_to_plan: "+ Add",
  exercise_no_exercises_found: "No exercises found",
  exercise_start_typing_to_search: "Start typing to search",
  exercise_back: "← Back",
  exercise_add_exercise_title: "Add exercise",
  exercise_error_start: "Could not start workout. Try again.",

  // ── EXERCISE SESSION SCREEN ───────────────────────────────────────────────
  session_time_label: "SESSION TIME",
  session_heart_rate_label: "HEART RATE",
  session_heart_rate_peak: "peak {bpm}",
  session_rest_label: "REST",
  session_done_resting: "Done resting",
  session_your_plan_label: "YOUR PLAN",
  session_logged_label: "LOGGED",
  session_tap_to_log: "Tap to log",
  session_hold_to_remove: "hold to remove",
  session_add_exercise: "+ Add exercise",
  session_start_button: "▶ Start",
  session_finish_button: "Finish",
  session_workout_complete: "Workout complete!",
  session_stat_exercises: "EXERCISES",
  session_stat_sets: "SETS",
  session_stat_time: "TIME",
  session_stat_peak_bpm: "PEAK BPM",

  // ── EXERCISE DETAIL SCREEN ────────────────────────────────────────────────
  exercise_detail_not_found: "Session not found.",
  exercise_detail_date_label: "DATE",
  exercise_detail_duration_label: "DURATION",
  exercise_detail_exercises_label: "EXERCISES",
  exercise_detail_avg_bpm_label: "AVG BPM",
  exercise_detail_peak_bpm_label: "PEAK BPM",
  exercise_detail_time_in_zone_label: "TIME IN ZONE",
  exercise_detail_heart_rate_label: "HEART RATE",
  exercise_detail_no_birthdate: "Add your birthdate in Settings → Preferences to see heart rate zones.",
  exercise_detail_exercises_logged: "EXERCISES LOGGED",
  exercise_detail_no_exercises: "No exercises logged in this session.",
  exercise_detail_max_weight_note: "All sets maxed — add weight next time",
  exercise_detail_zone_very_light: "Very light",
  exercise_detail_zone_light: "Light",
  exercise_detail_zone_moderate: "Moderate",
  exercise_detail_zone_hard: "Hard",
  exercise_detail_zone_maximum: "Maximum",

  // ── MINDFULNESS SCREEN ────────────────────────────────────────────────────
  mindfulness_choose_practice: "Choose a practice to begin.",
  mindfulness_breathing_title: "Breathing",
  mindfulness_grounding_title: "Grounding",
  mindfulness_meditation_title: "Meditation",
  mindfulness_gratitude_title: "Gratitude",
  mindfulness_back_to_practices: "Practices",
  mindfulness_cycles_completed: "Cycles completed: {n}",
  mindfulness_restart: "↺ RESTART",
  mindfulness_end_session: "END SESSION",
  mindfulness_remaining_label: "REMAINING",
  mindfulness_session_complete: "Session complete",
  mindfulness_guided_label: "Guided",
  mindfulness_guided_desc: "Follow along with spoken instructions",
  mindfulness_unguided_label: "Unguided",
  mindfulness_unguided_desc: "Meditate in silence with a timer",
  mindfulness_change_session_type: "← Change session type",
  mindfulness_change_duration: "← Choose a different duration",

  // ── EXPERIMENTS SCREEN ────────────────────────────────────────────────────
  experiments_title: "YOUR EXPERIMENTS",
  experiments_empty_title: "No experiments yet",
  experiments_empty_body: "Run a short personal experiment to discover what affects your energy, sleep, or mood.",
  experiments_start_button: "Start an experiment",
  experiments_status_active: "ACTIVE",
  experiments_status_completed: "COMPLETED",
  experiments_status_ended: "ENDED",
  experiments_view_results: "View Results",
  experiments_new_title: "NEW EXPERIMENT",
  experiments_what_will_you_try: "WHAT WILL YOU TRY?",
  experiments_intervention_placeholder: "e.g. Cut caffeine after 2pm",
  experiments_duration_label: "DURATION",
  experiments_metrics_label: "METRICS TO TRACK",
  experiments_metric_glucose: "Glucose TIR",
  experiments_metric_sleep: "Sleep",
  experiments_metric_mood: "Morning Mood",
  experiments_start_experiment: "Start Experiment",
  experiments_results_title: "RESULTS",
  experiments_before_vs_during: "BEFORE VS DURING",
  experiments_before_label: "Before:",
  experiments_during_label: "During:",
  experiments_error_create: "Could not create experiment.",
  experiments_error_load: "Could not load experiment results.",

  // ── INSIGHTS SCREEN ───────────────────────────────────────────────────────
  insights_tab_label: "Insights",
  insights_no_data: "Log mood, sleep, and meals for at least a week to unlock your personal insights.",
  insights_weekly_summary_title: "Weekly Summary",
  insights_top_insight_title: "Top Insight",
  insights_view_all: "View all",

  // ── INSIGHTS & TRENDS (SHARED) ────────────────────────────────────────────
  insights_trends_tab_insights: "Insights",
  insights_trends_tab_trends: "Trends",

  // ── TRENDS SCREEN ─────────────────────────────────────────────────────────
  trends_window_label: "window",
  trends_empty: "Log mood, sleep, and meals for at least a week to see your personal health patterns here.",
  trends_not_enough_data: "Not enough data yet — keep logging to reveal patterns.",
  trends_not_enough_overlap: "Not enough overlapping data yet — keep logging both to reveal patterns.",
  trends_pick_two_different: "Pick two different metrics to compare.",
  trends_compare_any_two_title: "Compare any two",
  trends_compare_subtitle: "Pick an X and Y axis to build your own scatter plot.",
  trends_x_axis_label: "X AXIS",
  trends_y_axis_label: "Y AXIS",
  trends_context_patterns_title: "Context Patterns",
  trends_context_patterns_subtitle: "Based on energy, stress, and social battery you logged during check-ins.",
  trends_days_with_data: "{n} days with data",
  trends_footnote: "Each dot is one day. Dashed line shows the overall trend.",
  trends_r_values: "r values",
  trends_r_based_on_window: "based on {n}-day window.",
  trends_corr_strong_positive: "Strong positive",
  trends_corr_strong_negative: "Strong negative",
  trends_corr_moderate_positive: "Moderate positive",
  trends_corr_moderate_negative: "Moderate negative",
  trends_corr_weak_positive: "Weak positive",
  trends_corr_weak_negative: "Weak negative",
  trends_corr_no_link: "No clear link",
  trends_tooltip_message: "Pick any two things to compare — sleep, mood, glucose, spending — and see how they move together over your logged days. Tap a chart to explore.",
  trends_metric_mood: "Mood",
  trends_metric_sleep: "Sleep",
  trends_metric_steps: "Steps",
  trends_metric_exercise: "Exercise",
  trends_metric_spending: "Spending",
  trends_metric_glucose: "Glucose",
  trends_metric_caffeine: "Caffeine",
  trends_metric_alcohol: "Alcohol",
  trends_card_sleep_mood: "Sleep ↔ Mood",
  trends_card_spending_mood: "Spending ↔ Mood",
  trends_card_glucose_mood: "Glucose ↔ Mood",
  trends_card_sleep_glucose: "Sleep ↔ Glucose",
  trends_card_caffeine_glucose: "Caffeine ↔ Glucose",
  trends_card_alcohol_sleep: "Alcohol ↔ Sleep",
  trends_card_caffeine_mood: "Caffeine ↔ Mood",
  trends_card_steps_mood: "Steps ↔ Mood",
  trends_card_exercise_mood: "Exercise ↔ Mood",
  trends_card_steps_sleep: "Steps ↔ Sleep",
  trends_card_exercise_sleep: "Exercise ↔ Sleep",

  // ── HISTORY SCREEN ────────────────────────────────────────────────────────
  history_title: "History",
  history_no_entries: "No entries found for this date.",
  history_load_more: "Load more",

  // ── STEPS DETAIL SCREEN ────────────────────────────────────────────────────
  steps_detail_title: "Steps",
  steps_detail_today: "Today",
  steps_detail_this_week: "This Week",
  steps_detail_average: "Daily average",
  steps_detail_best_day: "Best day",
  steps_detail_goal_label: "Goal",
  steps_detail_no_data: "No step data yet.",

  // ── GLOBAL SEARCH ─────────────────────────────────────────────────────────
  search_placeholder: "Search Ripple…",
  search_no_results: "No results found.",
  search_results_label: "Results",
  search_recent_label: "Recent",
  search_clear_recent: "Clear",

  // ── SETTINGS SCREEN ───────────────────────────────────────────────────────
  settings_title: "Settings",
  settings_account_section: "ACCOUNT",
  settings_app_section: "APP",
  settings_data_section: "DATA & INTEGRATIONS",
  settings_social_section: "SOCIAL",
  settings_support_section: "SUPPORT",
  settings_profile_row: "Profile",
  settings_appearance_row: "Appearance",
  settings_notifications_row: "Notifications",
  settings_preferences_row: "Preferences",
  settings_tab_settings_row: "Tab Settings",
  settings_security_row: "Security",
  settings_dexcom_row: "Dexcom Share",
  settings_health_connect_row: "Health Connect",
  settings_banks_row: "Connected Banks",
  settings_export_row: "Export & Backup",
  settings_social_settings_row: "Social & Friends",
  settings_medication_reminders_row: "Medication Reminders",
  settings_tracking_row: "Always-on Tracking",
  settings_help_row: "Help & FAQ",
  settings_sign_out: "Sign out",
  settings_sign_out_confirm: "Sign out",
  settings_sign_out_cancel: "Cancel",
  settings_sign_out_alert_title: "Sign out?",
  settings_sign_out_alert_message: "You will be logged out of your account.",
  settings_version_label: "Version",

  // ── APPEARANCE SETTINGS ───────────────────────────────────────────────────
  appearance_theme_title: "THEME",
  appearance_theme_desc: "Choose a colour palette for the entire app.",
  appearance_shadows_title: "SHADOWS",
  appearance_shadows_desc: "Card shadows add depth and dimensionality. Turn off for a flatter look.",
  appearance_shadows_row_label: "Card & tile shadows",
  appearance_shadows_enabled_desc: "Bold offset shadows enabled",
  appearance_shadows_disabled_desc: "Flat cards, no shadow",
  appearance_opacity_title: "CARD OPACITY",
  appearance_opacity_desc: "Lower opacity lets page backgrounds show through cards — useful with background images.",
  appearance_opacity_100_hint: "Fully opaque — maximum readability",
  appearance_opacity_90_hint: "Slightly transparent — subtle",
  appearance_opacity_75_hint: "Noticeably transparent — good with background images",
  appearance_opacity_50_hint: "Highly transparent — ensure text stays readable",
  appearance_opacity_reset_label: "Reset to theme default",
  appearance_font_family_title: "FONT",
  appearance_font_family_desc: "Choose a typeface for the app. All options are system fonts — no download required.",
  appearance_font_scale_title: "TEXT SIZE",
  appearance_font_scale_desc: "Scale text up or down. Works alongside your system accessibility font size.",

  // ── PREFERENCES SETTINGS ─────────────────────────────────────────────────
  preferences_profile_section: "PROFILE",
  preferences_tanaka_note: "Used for heart rate zone calculations (Tanaka formula).",
  preferences_date_of_birth_label: "Date of birth",
  preferences_saved_indicator: "Saved ✓",
  preferences_save_button: "Save",
  preferences_home_section: "HOME SCREEN",
  preferences_home_note: "Choose which sections appear on your home screen.",
  preferences_open_customizer: "Open customizer →",
  preferences_week_start_section: "WEEK START DAY",
  preferences_week_start_desc: "Choose which day your week starts on (affects hobby and finance summaries).",

  // ── SECURITY SETTINGS ─────────────────────────────────────────────────────
  security_title: "Security",
  security_change_password: "Change password",
  security_current_password_placeholder: "Current password",
  security_new_password_placeholder: "New password",
  security_confirm_password_placeholder: "Confirm new password",
  security_save_password: "Save new password",
  security_error_passwords_dont_match: "Passwords don't match.",
  security_error_current_required: "Current password required.",
  security_error_new_required: "New password required.",
  security_success_changed: "Password changed successfully.",

  // ── NOTIFICATIONS SETTINGS ────────────────────────────────────────────────
  notif_silence_all_title: "SILENCE ALL",
  notif_muted_until: "Muted until {time}",
  notif_clear_mute: "Clear mute",
  notif_battery_title: "BATTERY",
  notif_battery_desc: "Battery optimization can delay or block background notifications. Exempt Ripple to keep reminders reliable.",
  notif_battery_exempt: "Battery optimization ✓ exempt (good)",
  notif_battery_restricted: "Battery optimization ⚠ restricted",
  notif_open_settings: "Open settings",
  notif_section_health: "Health",
  notif_section_meals: "Meals",
  notif_section_reminders: "Reminders",
  notif_glucose_spike_title: "GLUCOSE SPIKE",
  notif_glucose_spike_desc: "Asks if you ate something when glucose rises 30+ mg/dL in an hour.",
  notif_glucose_spike_toggle: "Prompt on glucose spike",
  notif_glucose_threshold_title: "GLUCOSE THRESHOLDS",
  notif_glucose_threshold_desc: "Alerts when glucose goes below or above fixed boundaries.",
  notif_glucose_threshold_toggle: "Low/high glucose alerts",
  notif_glucose_low_label: "Low alert (mg/dL)",
  notif_glucose_high_label: "High alert (mg/dL)",
  notif_step_goal_title: "STEP GOAL",
  notif_step_goal_desc: "Alerts when you're close to your daily step goal and celebrates when you hit it.",
  notif_step_goal_toggle: "Step goal alerts",
  notif_step_goal_daily_label: "Daily goal",
  notif_bedtime_title: "BEDTIME REMINDER",
  notif_bedtime_desc: "Reminds you to start winding down at your target bedtime.",
  notif_bedtime_toggle: "Bedtime reminder",
  notif_workout_title: "WORKOUT REMINDER",
  notif_workout_desc: "Nudges you when you haven't had a completed workout session in a while.",
  notif_workout_toggle: "Remind me to work out",
  notif_workout_days_label: "Remind after (days inactive)",
  notif_cycle_title: "CYCLE REMINDERS",
  notif_cycle_enable_first: "Enable the Cycle tracker in Tab Settings to use cycle reminders.",
  notif_period_approaching_toggle: "Period approaching reminder",
  notif_period_lead_days_label: "Days before to remind",
  notif_cycle_log_toggle: "Daily cycle log reminder (optional)",
  notif_meal_title: "MEAL REMINDERS",
  notif_meal_toggle: "Remind me to log meals",
  notif_breakfast_label: "Breakfast",
  notif_lunch_label: "Lunch",
  notif_dinner_label: "Dinner",
  notif_water_title: "WATER REMINDER",
  notif_water_desc: "Nudges every 2 hours if you haven't hit your daily glass goal.",
  notif_water_toggle: "Remind me to drink water",
  notif_water_start_label: "Start at",
  notif_evening_checkin_title: "EVENING CHECK-IN",
  notif_evening_checkin_toggle: "Daily end-of-day summary",
  notif_mood_checkin_title: "MOOD CHECK-IN",
  notif_mood_checkin_desc: "Nudges you to log a mood check-in if you haven't yet.",
  notif_mood_checkin_toggle: "Remind me to check in",
  notif_streak_title: "STREAK PROTECTION",
  notif_streak_desc: "Warns you before midnight if you haven't logged today and have an active streak.",
  notif_streak_toggle: "Protect my streak",
  notif_medication_title: "MEDICATION REMINDERS",
  notif_medication_desc: "Reminds you when each time-of-day medication slot is due and hasn't been logged.",
  notif_medication_toggle: "Medication reminders",
  notif_medication_morning_label: "Morning reminder",
  notif_medication_midday_label: "Midday reminder",
  notif_medication_evening_label: "Evening reminder",
  notif_mindfulness_title: "MINDFULNESS REMINDER",
  notif_mindfulness_desc: "Daily nudge to take a few minutes for breathing or meditation.",
  notif_mindfulness_toggle: "Remind me to practice",
  notif_reading_title: "READING REMINDER",
  notif_reading_desc: "Reminds you to log reading time if you have a book in progress.",
  notif_reading_toggle: "Remind me to read",
  notif_activity_title: "ACTIVITY REMINDER",
  notif_activity_desc: "Reminds you to log a hobby or activity if you have any set up.",
  notif_activity_toggle: "Remind me to log activities",
  notif_spending_title: "SPENDING ALERTS",
  notif_spending_desc: "Notifies you when today's spending exceeds your daily budget.",
  notif_spending_toggle: "Daily budget alert",
  notif_spending_budget_label: "Daily budget ($)",
  notif_error_save: "Failed to save.",
  notif_error_title: "Error",

  // ── DEXCOM SETTINGS ────────────────────────────────────────────────────────
  dexcom_credentials_title: "CREDENTIALS",
  dexcom_credentials_note: "Enter your Dexcom Share account credentials. These are separate from your Dexcom mobile app login.",
  dexcom_account_id_label: "Account ID",
  dexcom_account_id_placeholder: "Dexcom Share username",
  dexcom_password_label: "Password",
  dexcom_password_placeholder: "Dexcom Share password",
  dexcom_region_label: "Region",
  dexcom_region_us: "US",
  dexcom_region_outside_us: "Outside US",
  dexcom_save_button: "Save credentials",
  dexcom_error_save: "Could not save credentials.",
  dexcom_success_save: "Credentials saved.",
  dexcom_clear_confirm_title: "Clear credentials?",
  dexcom_clear_confirm_message: "This will remove your saved Dexcom credentials.",
  dexcom_clear_confirm_ok: "Clear",
  dexcom_clear_confirm_cancel: "Cancel",

  // ── HEALTH CONNECT SETTINGS ───────────────────────────────────────────────
  health_connect_permissions_title: "PERMISSIONS",
  health_connect_permissions_label: "Health Connect permissions",
  health_connect_permissions_granted: "Granted",
  health_connect_permissions_not_granted: "Not granted",
  health_connect_grant_button: "Grant Health Connect permissions",
  health_connect_auto_sync_title: "AUTO-SYNC",
  health_connect_auto_sync_toggle: "Sync automatically on open",
  health_connect_manual_sync_title: "MANUAL SYNC",
  health_connect_sync_now_button: "Sync now",
  health_connect_syncing: "Syncing…",
  health_connect_live_tracking_title: "LIVE TRACKING",
  health_connect_live_tracking_desc: "Keeps step and heart rate data up to date in the background.",
  health_connect_live_tracking_toggle: "Always-on tracking",
  health_connect_battery_exemption: "Battery optimization exemption",
  health_connect_android_only: "Health Connect is Android only.",
  health_connect_error_permissions: "Could not check permissions.",
  health_connect_error_sync: "Sync failed.",
  health_connect_success_sync: "Synced successfully.",

  // ── BANKS SETTINGS ────────────────────────────────────────────────────────
  banks_connect_title: "Connect a bank",
  banks_connected_title: "CONNECTED BANKS",
  banks_bank_account_fallback: "Bank account",
  banks_last_synced: "Last synced {date}",
  banks_remove_button: "Remove",
  banks_sync_now_button: "Sync now",
  banks_plaid_disclaimer: "Bank connection powered by Plaid. Ripple only reads transaction data — no write access.",
  banks_empty_title: "No banks connected",
  banks_empty_body: "Connect a bank to automatically import transactions.",
  banks_connect_button: "Connect a bank",
  banks_error_connect: "Could not connect bank.",
  banks_error_sync: "Could not sync transactions.",
  banks_error_remove: "Could not remove bank.",
  banks_success_sync: "Transactions synced.",
  banks_disconnect_alert_title: "Disconnect bank?",
  banks_disconnect_alert_message: "This will remove the bank connection and stop syncing transactions.",
  banks_disconnect_alert_confirm: "Disconnect",
  banks_disconnect_alert_cancel: "Cancel",

  // ── EXPORT & BACKUP SETTINGS ──────────────────────────────────────────────
  export_health_report_title: "HEALTH REPORT",
  export_health_report_desc: "Generate a PDF summary of your health data for a date range — useful for doctor visits.",
  export_start_date_label: "Start date",
  export_end_date_label: "End date",
  export_generate_pdf: "Generate & share PDF",
  export_full_data_title: "FULL DATA EXPORT",
  export_full_data_desc: "Download a complete JSON backup of all your Ripple data.",
  export_download_backup: "Download full backup",
  export_google_drive_title: "GOOGLE DRIVE",
  export_google_drive_desc: "Back up your data nightly to Google Drive automatically.",
  export_drive_connect_button: "Connect Google Drive",
  export_drive_connected: "Connected",
  export_drive_backup_now: "Back up now",
  export_drive_disconnect: "Disconnect",
  export_drive_last_backup: "Last backup: {date}",
  export_drive_never_backed_up: "Never backed up",
  export_error_pdf: "Could not generate PDF.",
  export_error_json: "Could not export data.",
  export_error_drive: "Could not connect Google Drive.",
  export_success_backup: "Backup complete.",

  // ── TRACKING SETTINGS ─────────────────────────────────────────────────────
  tracking_title: "ALWAYS-ON TRACKING",
  tracking_desc: "Keeps your health data syncing in the background so Ripple stays up to date without you having to open the app.",
  tracking_notification_label: "Always-on tracking notification",
  tracking_status_running: "Running",
  tracking_status_stopped: "Stopped",
  tracking_status_error: "Error",
  tracking_notification_perm_label: "Notification permission",
  tracking_notification_perm_granted: "Granted",
  tracking_notification_perm_denied: "Denied",
  tracking_open_notification_settings: "Open notification settings",
  tracking_android_only: "Always-on tracking is Android only.",
  tracking_error_start: "Could not start tracking.",
  tracking_error_stop: "Could not stop tracking.",

  // ── MEDICATION REMINDERS SETTINGS ─────────────────────────────────────────
  med_reminders_no_meds: "No medications found",
  med_reminders_import_hint: "Add medications in the Health tab, then configure reminder times here.",
  med_reminders_daily_desc: "Set a daily reminder time for each medication.",
  med_reminders_time_placeholder: "HH:MM",
  med_reminders_add_button: "ADD",
  med_reminders_save_button: "SAVE REMINDERS",
  med_reminders_error_save: "Could not save reminders.",
  med_reminders_success_save: "Reminders saved.",

  // ── TAB PREFERENCES SCREEN ────────────────────────────────────────────────
  tab_prefs_choose_title: "Choose your tabs",
  tab_prefs_manage_title: "Manage tabs",
  tab_prefs_pick_up_to: "Pick up to {max}. Change any time from Settings.",
  tab_prefs_health_includes: "Health tab includes:",
  tab_prefs_medication_option: "Medication",
  tab_prefs_cycle_option: "Menstrual cycle",
  tab_prefs_single_tab_note: "If only one is on, the Health tab opens straight to it.",
  tab_prefs_selected_count: "{count} of {max} selected",
  tab_prefs_cancel: "Cancel",
  tab_prefs_continue: "Continue  →",
  tab_prefs_save: "Save",
  tab_prefs_alert_min_title: "At least 2 tabs required",
  tab_prefs_alert_min_message: "Please select at least 2 tabs.",
  tab_prefs_alert_max_title: "Maximum {max} tabs",
  tab_prefs_alert_max_message: "Please deselect a tab before adding another.",
  tab_prefs_alert_ok: "OK",

  // ── WORKOUT SETUP WIZARD ──────────────────────────────────────────────────
  workout_wizard_step_counter: "STEP {current} OF {total}",
  workout_wizard_building_plan: "Building your plan…",
  workout_wizard_your_plan_title: "Your starter plan",
  workout_wizard_plan_summary: "{days} day(s)/week · {minutes} min per session",
  workout_wizard_use_plan: "✓ Use this plan",
  workout_wizard_change_answers: "↺ Change answers",
  workout_wizard_skip_build_own: "Skip — I'll build my own sessions",
  workout_wizard_skip_manual: "Skip setup — I'll build sessions manually",
  workout_wizard_generate_plan: "Generate my plan →",
  workout_wizard_back: "← Back",
  workout_wizard_next: "Next →",
  workout_wizard_skip_step: "Skip →",
  workout_wizard_medical_disclaimer: "Consult a healthcare professional before starting any new exercise program, especially if you have a medical condition.",
  workout_wizard_alert_select_one: "Please select at least one option.",
  workout_wizard_error_generate: "Could not generate a plan. Please try again.",

  // ── MEDICATION IMPORT SCREEN ──────────────────────────────────────────────
  med_import_title: "Import Medications",
  med_import_file_desc: "Import from a CSV or Excel file. Download the blank template to get the correct column format.",
  med_import_choose_file: "Choose file…",
  med_import_download_template: "Download blank template (.xlsx)",
  med_import_map_columns: "Map columns",
  med_import_rows_count: "{count} row(s) · tap any row to change mapping",
  med_import_not_mapped: "— not mapped",
  med_import_preview_title: "PREVIEW (first 3 rows)",
  med_import_field_name: "Name",
  med_import_field_dosage: "Dosage",
  med_import_field_purpose: "Purpose",
  med_import_field_notes: "Notes",
  med_import_field_prescriber: "Prescriber",
  med_import_field_refill_date: "Refill date",
  med_import_field_brand_name: "Brand name",
  med_import_field_generic_name: "Generic name",
  med_import_required_indicator: " *",
  med_import_success_title: "Import complete!",
  med_import_success_body: "{count} medication(s) added to your schedule.",
  med_import_done_button: "Done",
  med_import_error_file: "Could not read file.",
  med_import_error_import: "Import failed. Please check your file format.",

  // ── MEDICATION HISTORY SCREEN ─────────────────────────────────────────────
  med_history_title: "CHANGE HISTORY",
  med_history_empty: "No changes recorded yet.",
  med_history_change_added: "Added",
  med_history_change_dose: "Dose changed",
  med_history_change_schedule: "Schedule changed",
  med_history_change_prescriber: "Prescriber changed",
  med_history_change_stopped: "Stopped",
  med_history_reason_prefix: "Reason:",
  med_history_by_prefix: "By:",

  // ── HELP SCREEN ───────────────────────────────────────────────────────────
  help_replay_tour_title: "Replay app tour",
  help_replay_tour_subtitle: "Walk through each section of Ripple again",
  help_intro: "Find answers to common questions about Ripple Wellness.",
  help_section_getting_started: "Getting Started",
  help_section_glucose: "Glucose",
  help_section_meals: "Meals & Food",
  help_section_books_hobbies: "Books & Hobbies",
  help_section_notifications: "Notifications",
  help_section_privacy: "Privacy & Data",

  // ── FEATURE TOUR ──────────────────────────────────────────────────────────
  feature_tour_counter: "{current} of {total}",
  feature_tour_skip: "Skip",
  feature_tour_next: "Next  →",
  feature_tour_done: "Got it",

  // ── SECTION EDITOR MODAL ─────────────────────────────────────────────────
  section_editor_show_all: "Show all",
  section_editor_done: "Done",
  section_editor_hint: "Hide sections you don't use to keep this screen focused.",
  section_editor_status_shown: "Shown",
  section_editor_status_hidden: "Hidden",

  // ── RECIPE BUILDER MODAL ──────────────────────────────────────────────────
  recipe_new_title: "New recipe",
  recipe_edit_title: "Edit recipe",
  recipe_step_name: "Name",
  recipe_step_ingredients: "Ingredients",
  recipe_step_review: "Review",
  recipe_name_label: "Recipe name",
  recipe_name_placeholder: "e.g. My morning smoothie",
  recipe_next_button: "Next — add ingredients",
  recipe_search_label: "Search food to add",
  recipe_search_placeholder: "search food...",
  recipe_ingredients_count: "INGREDIENTS ({count})",
  recipe_ingredient_single: "INGREDIENT",
  recipe_no_macro_data: "no macro data",
  recipe_back: "← Back",
  recipe_review_button: "Review →",
  recipe_edit_back: "← Edit",
  recipe_combined_macros: "COMBINED MACROS",
  recipe_save_button: "Save recipe",
  recipe_save_changes_button: "Save changes",
  recipe_error_save: "Couldn't save recipe",
  recipe_error_save_message: "Check your connection and try again.",
  recipe_macro_cal: "cal",
  recipe_macro_carbs: "carbs",
  recipe_macro_sugar: "sugar",

  // ── BARCODE SCANNER MODAL ─────────────────────────────────────────────────
  barcode_scan_food: "Scan food barcode",
  barcode_scan_caffeine: "Scan caffeine barcode",
  barcode_scan_alcohol: "Scan alcohol barcode",
  barcode_camera_required: "Camera access is required to scan barcodes.",
  barcode_grant_permission: "Grant permission",
  barcode_point_camera: "Point camera at a barcode",
  barcode_looking_up: "Looking up product…",
  barcode_not_found_caffeine: "No caffeine data found for this product.",
  barcode_not_found_alcohol: "No alcohol data found for this product.",
  barcode_not_found_food: "Product not found. Try searching by name instead.",
  barcode_enter_manually: "Enter manually",
  barcode_scan_again: "Scan again",
  barcode_lookup_failed: "Barcode lookup failed",

  // ── WORKOUT PLANNER MODAL ─────────────────────────────────────────────────
  workout_planner_title: "Plan your workout",
  workout_planner_no_exercises_title: "No exercises planned",
  workout_planner_no_exercises_body: "Add exercises below to build your workout, or begin now and log as you go.",
  workout_planner_exercises_label: "EXERCISES",
  workout_planner_est_time_label: "EST. TIME",
  workout_planner_now_label: "NOW",
  workout_planner_add_exercise: "+ Add exercise",
  workout_planner_begin: "Begin Workout",
  workout_planner_cancel: "Cancel",
  workout_planner_search_placeholder: "Search exercises…",
  workout_planner_add_chip: "+ Add",
  workout_planner_back: "← Back",
  workout_planner_add_exercise_title: "Add exercise",
  workout_planner_no_exercises_found: "No exercises found",
  workout_planner_start_typing: "Start typing to search",
  workout_planner_error_start: "Could not start workout. Try again.",

  // ── DEFINED TERMS (GLOSSARY) ──────────────────────────────────────────────
  defined_term_time_in_range_title: "Time in Range",
  defined_term_time_in_range_body: "The percentage of your glucose readings that fell between 70 and 180 mg/dL in the selected time window. A higher percentage means your glucose spent more of that period in a typical healthy range.",
  defined_term_pearson_r_title: "Correlation (r value)",
  defined_term_pearson_r_body: "A number between −1 and +1 that shows how closely two things move together over the logged days. Near +1 means they tend to rise and fall together. Near −1 means when one rises the other tends to fall. Near 0 means no consistent pattern. Values below ±0.35 generally indicate no meaningful link.",
  defined_term_mg_dl_title: "mg/dL",
  defined_term_mg_dl_body: "Milligrams per deciliter — the unit used to measure glucose concentration in your blood. The commonly referenced target range is 70–180 mg/dL.",
  defined_term_standard_drink_title: "Standard Drink",
  defined_term_standard_drink_body: "A standardised unit of alcohol — roughly 14 g of pure ethanol, equivalent to a 355 ml (12 oz) regular beer, 148 ml (5 oz) wine, or 44 ml (1.5 oz) spirit. Used to make comparisons consistent across different drink types.",
  defined_term_close: "CLOSE",

  // ── TOOLTIP BUBBLE ────────────────────────────────────────────────────────
  tooltip_got_it: "Got it",

  // ── OFFLINE / SYNC BANNERS ────────────────────────────────────────────────
  offline_banner_message: "You're offline — some features may be unavailable.",
  stale_sync_banner_message: "Data may be out of date — tap to sync.",
  stale_sync_banner_action: "Sync",
  undo_banner_message: "Undo",

  // ── MOOD CHECK-IN MODAL ───────────────────────────────────────────────────
  mood_checkin_title: "How are you feeling?",
  mood_checkin_mood_label: "Mood",
  mood_checkin_energy_label: "Energy",
  mood_checkin_stress_label: "Stress",
  mood_checkin_social_label: "Social Battery",
  mood_checkin_notes_placeholder: "Notes (optional)…",
  mood_checkin_save_button: "Save",
  mood_checkin_skip_button: "Skip",
  mood_checkin_saved: "Check-in saved",
  mood_checkin_error: "Could not save check-in.",

  // ── DASHBOARD EDITOR MODAL ────────────────────────────────────────────────
  dashboard_editor_title: "Customize",
  dashboard_editor_done: "Done",
  dashboard_editor_reset: "Reset",

  // ── COMMON / SHARED ───────────────────────────────────────────────────────
  common_cancel: "Cancel",
  common_save: "Save",
  common_delete: "Delete",
  common_remove: "Remove",
  common_done: "Done",
  common_ok: "OK",
  common_close: "Close",
  common_back: "Back",
  common_next: "Next",
  common_skip: "Skip",
  common_edit: "Edit",
  common_retry: "Retry",
  common_loading: "Loading…",
  common_saving: "Saving…",
  common_error_generic: "Something went wrong. Please try again.",
  common_error_network: "Could not connect. Check your internet connection.",
  common_no_data: "No data available.",
  common_unavailable: "Unavailable",

} as const;

export type StringKey = keyof typeof DEFAULT_STRINGS;
export type StringMap = { [K in StringKey]: string };
